### ISSUE TITLE
Type-ahead removes strings when wildcards used

### ISSUE THREAD

**Issue by sephcoster** [cfpb/ccdb5-ui#116]
Type-ahead previews are currently showing strange text when advanced search wildcards are used. Likely an issue with normalizing to .toLowercase() and special characters not getting same treatment from indexOf().

## Current behavior
![screen shot 2017-11-02 at 5 35 54 pm](https://user-images.githubusercontent.com/1028659/32351600-5727f91c-bff4-11e7-9a89-4ba449520976.png)

Selections work just fine, happily. It's just the selector that removes the trailing characters.

## Expected behavior
Entering text rate* yields `rate change` instead of `e change` in preview.

## Steps to replicate behavior (include URLs)

1. Navigate to environment.
1. Enter `rate*` as search criteria
1. See type-ahead selector component

**Comment by JeffreyMFarley** [comment]
Here is one way to fix it:

![screen shot 2017-11-03 at 9 43 05 am](https://user-images.githubusercontent.com/8754176/32376572-895fa7f4-c07b-11e7-88d2-ab23885dc128.png)
