### ISSUE TITLE
User-Agent HTTP header is assumed

### ISSUE THREAD

**Issue by chosak** [cfpb/ccdb5-ui#128]
The code [here](https://github.com/cfpb/ccdb5-ui/blob/master/ccdb5_ui/views.py#L29) assumes that the Django request object always have a `META['HTTP_USER_AGENT']` value, which cannot be assumed. This value gets created from the HTTP request's `User-Agent` header ([see Django docs](https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpRequest.META)), which may not always exist.

A simple fix here might be to change the code from `request.META['HTTP_USER_AGENT']` to `request.META.get('HTTP_USER_AGENT')`, and handle the case where the value doesn't exist.

## Current behavior

Requests with a search query but no user agent cause a 500 error.

## Expected behavior

Requests with a search query but no user agent are handled properly.

## Steps to replicate behavior (include URLs)

1. Try this curl command, which omits the `User-Agent` header:

```sh
curl -v -H "User-Agent:" https://www.consumerfinance.gov/data-research/consumer-complaints/search/?searchField=company
```

This raises a 500 error.

**Comment by JeffreyMFarley** [comment]
@chosak This should be on the `ccdb5-api` repo
