### ISSUE TITLE
432020

### ISSUE THREAD

**Issue by weldingham** [cfpb/ccdb5-ui#222]
Short description explaining the high-level reason for the new issue.

## Current behavior
<Browsing around in my neighborhood>

## Steps to replicate behavior (include URLs)

1.To if this issues is done correctly

**Comment by sephcoster** [comment]
Hello @weldingham - I'm not quite sure of the specific question or issue you are having based on your post. If it's OK, I'd like to close this. Please feel free to re-open / update if there is a specific question? Thanks!
