### ISSUE TITLE
432020/11:9

### ISSUE THREAD

**Issue by weldingham** [cfpb/ccdb5-ui#223]
Short description explaining the high-level reason for the new issue.

## Steps to replicate behavior (include URLs)

1. I will be interesting to no everything behind ccdb-ui
2.Ok Let deal with Current behavior expected behavior
3 What goes in between

**Comment by weldingham** [comment]
Making three changes without a bog

**Comment by weldingham** [comment]
Where can i find your respond

**Comment by sephcoster** [comment]
Hello @weldingham - I'm having trouble understanding your question or issue. Could you please let us know what you would like to know about CCDB-UI and/or the issue you are having and we'll respond as best as we can? Thanks!

**Comment by sephcoster** [comment]
Closing this @weldingham but feel free to re-open if you can provide a bit more detail about your question. Thanks!
