### ISSUE TITLE
Upgrade NPM dependencies

### ISSUE THREAD

**Issue by sebworks** [cfpb/ccdb5-ui#25]
I would consider upgrading the NPM dependencies, especially Webpack, to the latest versions .  There are some great features in Webpack 2.x and 3.x. https://webpack.github.io/docs/roadmap.html.

**Comment by JeffreyMFarley** [comment]
I tried that, but the LESS plugin is not available for the latest version yet

**Comment by sebworks** [comment]
ok, I'll check it out today.  I think people are starting to upgrade: https://github.com/facebookincubator/create-react-app/issues/2573.

**Comment by sebworks** [comment]
It looks like `less-loader` just added support for webpack 3: https://github.com/webpack-contrib/less-loader/releases/tag/v4.0.5.

**Comment by JeffreyMFarley** [comment]
`2 days ago`.   Well, there it is

**Comment by sebworks** [comment]
@JeffreyMFarley, ok I've added a basic process: #32. I didn't merge in the modifications you made to the linter file on your branch though.

**Comment by JeffreyMFarley** [comment]
Notes on my first attempt to address this issue https://gist.github.com/JeffreyMFarley/2fc381f9b45c804242aea854165ec628

**Comment by sebworks** [comment]
Ok, I'm going to give it go.
