### ISSUE TITLE
To discover

### ISSUE THREAD

**Issue by weldingham** [cfpb/ccdb5-ui#252]
Short description explaining the high-level reason for the new issue.

## Current behavior
+ Thinking is this a distraction of my main objective

## Expected behavior
+ Time to leave cores-ponder alone, I see you ever where

## Steps to replicate behavior (include URLs)

1+ llovy4545@o

**Comment by sephcoster** [comment]
@weldingham I can't quite make out your issue, but your expected behavior text gives me a lot to think about. Closing for now but feel free to re-open if you still have an issue.
