### ISSUE TITLE
Configure ESLint to use the front-end standard

### ISSUE THREAD

**Issue by sebworks** [cfpb/ccdb5-ui#26]
Modify the linting process to use the front-end linting [file](https://github.com/cfpb/development/blob/master/.eslintrc).  Adjustments might need to be made for React and JSX.

**Comment by JeffreyMFarley** [comment]
> Adjustments might need to be made for React and JSX.

Yep!

**Comment by sebworks** [comment]
@JeffreyMFarley, I can create a PR if you would like.

**Comment by JeffreyMFarley** [comment]
@sebworks I started work on this in a branch https://github.com/JeffreyMFarley/ccdb5-ui/commits/lint.  I wasn't going to work on it until we have more of the functionality finished and I have a chance to adjust our current code base.

I do want to see what you have so far!

**Comment by sebworks** [comment]
@JeffreyMFarley, I have an sand sandwach right now but I'll work on it today.

**Comment by sebworks** [comment]
@JeffreyMFarley, ok I've added a basic process: #32. I didn't merge in the modifications you made to the linter file on your branch though.

**Comment by JeffreyMFarley** [comment]
There are some warnings to clean up, but the core of this issue has been addressed
