### ISSUE TITLE
Use bindAll

### ISSUE THREAD

**Issue by JeffreyMFarley** [cfpb/ccdb5-ui#46]
This issue was raised [as part of PR #40](https://github.com/cfpb/ccdb5-ui/pull/40#pullrequestreview-53734558).

## Current behavior

In some constructors, there is a block of code that looks like this:

```javascript
    this._handleSubmit = this._handleSubmit.bind(this);
    this._updateInputValue = this._updateInputValue.bind(this);
```

This is necessary so that `this` is available in callbacks.
https://facebook.github.io/react/docs/handling-events.html

## Expected behavior

@sebworks suggested using a `bindAll` utility function to simplify/ease this code block.

https://stackoverflow.com/questions/32192682/react-js-es6-avoid-binding-this-to-every-method
https://www.npmjs.com/package/lodash.bindall

**Comment by sephcoster** [comment]
I understand that this creates some unsightly boilerplate bindings, but is there a significant enough utility  / readability improvement to reducing these statements that it's worth introducing another dependency or potential breakage of ecosystem tooling in development? (react-hot-loader was mentioned in the linked StackOverflow article)

If the risk is low and we think this would significantly improve the application's readability that's fine -  personally they're not too big an impediment and I'd prioritize keeping risk to the app / dev workflow as low as possible.

**Comment by sebworks** [comment]
yeah, It's your choice. This is this function from underscore:

```
 _.bindAll = function(obj) {
    var i, length = arguments.length, key;
    if (length <= 1) throw new Error('bindAll must be passed function names');
    for (i = 1; i < length; i++) {
      key = arguments[i];
      obj[key] = _.bind(obj[key], obj);
    }
    return obj;
  };
```

**Comment by JeffreyMFarley** [comment]
`bindAll` is now part of the codebase, but is not deployed to every module.  Will close this issue since the ability exists and the code can be refactored when it is revisited
