### ISSUE TITLE
Clean up `example-input`

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/ccdb5-ui#515]
There are `example-input` classes that appear to have no styles attached to them. 

There are also `example-input__full` classes that do have styles, but these are coded to be elements of a parent `example-input`, which they are not. 

I'd suggest removing the existing `example-input` entries, and renaming the `example-input__full` entries to `example-input`.

**Comment by flacoman91** [comment]
DATAP-1569 for tracking

**Comment by flacoman91** [comment]
Fixed in latest code
