### ISSUE TITLE
Copy/paste company name leads to stuck "Type to search…"

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/ccdb5-ui#531]
## Steps to replicate behavior (include URLs)

1. Copy/paste a company name in the search and it'll be stuck showing "Type to search…"

## Screenshots

<img width="364" alt="Screenshot 2024-08-23 at 1 06 52 PM" src="https://github.com/user-attachments/assets/287a30ad-521e-4029-957d-ba1496025799">

**Comment by flacoman91** [comment]
fix here:
https://github.com/cfpb/ccdb5-ui/pull/482

**Comment by flacoman91** [comment]
Fixed in latest code
