### ISSUE TITLE
After switching to Node 8, Travis is no longer pushing assets

### ISSUE THREAD

**Issue by JeffreyMFarley** [cfpb/ccdb5-ui#78]
There is a problem where `package-lock.json` is not part of the commit

**Comment by JeffreyMFarley** [comment]
What I was getting

```
npm ERR! Git working directory not clean.
npm ERR! M package-lock.json
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-09-08T15_12_25_740Z-debug.log
```

### Theory:

If `package-lock.json` is out-of-synch when `npm install` is run, it gets 
updated and is dirty when we are trying to run `npm version`

Add `git checkout -- .` before `npm version`

### Execution

It total worked 🎉

**Comment by SKempin** [comment]
Fixed it for me too, I was having the same error but with `package.json`

```
- git checkout -- .
- npm version patch
```

**Comment by evonsdesigns** [comment]
I commit my `package-lock.json` file, but still see this error. My fix was to change the npm script from `npm i` to `npm ci` to install dependencies from the package-lock file.
